name: CI/CD

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:  # Allow manually running the workflow

jobs:
  test_job:
    name: test CI/CD
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello World!"
#      - name: Set up Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: '22.x'

#      - name: Install Dependencies
#        run: 
#          npm install
#          npm install say
        
